language: java

jdk:
- oraclejdk8

before_install:
- wget http://services.gradle.org/distributions/gradle-4.9-bin.zip
- unzip gradle-4.9-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.9
- export PATH=$GRADLE_HOME/bin:$PATH
